### ISSUE TITLE
ValueError: Invalid path

### ISSUE THREAD

**Issue by gerroon** [spl0k/supysonic#102]
Not sure, I am not a dev but I get this error during scan

I am using it on Debian testing, and used pip install . method

```
98806 files scannedTraceback (most recent call last):                                                                                          [5/69]
  File "/usr/local/bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 36, in pony_wrapper                                                                            
    return caller(func, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 460, in new_func                                                                                  
    try: return func(*args, **kwargs)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/cli.py", line 67, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/usr/local/lib/python2.7/dist-packages/supysonic/cli.py", line 175, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/usr/local/lib/python2.7/dist-packages/supysonic/scanner.py", line 94, in scan
    cover = find_cover_in_folder(f.path, album_name)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/covers.py", line 63, in find_cover_in_folder
    raise ValueError('Invalid path')
ValueError: Invalid path
```

**Comment by spl0k** [comment]
Did it happen during a scan after you moved or removed media files? It looks like the same error than in #101.

**Comment by gerroon** [comment]
@spl0k 

NO it crashes when scanning a new media folder added via the cli or in the web page. I have 2 media foilders. One scans fine, but it borks at another. I use the same folders with Airsonic, its scanner does not seem to have issue with it.

**Comment by spl0k** [comment]
Just in case, I pushed a fix for #101, could you test again if the problem still occurs please?
If it's still there: would you happen to have "special" folders, such as symbolic links (even if they're not supported) or weird permissions on folders?

**Comment by gerroon** [comment]
I still get same or similar message. All my music folders are 777, I have multiple media servers (including airsonic) scanning the same folders without borking. 

```
 supysonic-cli folder scan Music
Scanning 'Music': 78293 files scannedTraceback (most recent call last):
  File "/usr/local/bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 36, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 460, in new_func
    try: return func(*args, **kwargs)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/cli.py", line 67, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/usr/local/lib/python2.7/dist-packages/supysonic/cli.py", line 175, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/usr/local/lib/python2.7/dist-packages/supysonic/scanner.py", line 94, in scan
    cover = find_cover_in_folder(f.path, album_name)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/covers.py", line 63, in find_cover_in_folder
    raise ValueError('Invalid path')
ValueError: Invalid path

```

**Comment by spl0k** [comment]
The `find_cover_in_folder()` is no longer on line 94 of _scanner.py_, you have to upgrade your installation. It can be done by running the install command, either
```
pip install .
```
or
```
python setup.py install
```

In the meantime I'll run some tests with removable drives.

**Comment by gerroon** [comment]
See this

```
supysonic-cli folder scan Music
Scanning 'Muzik': 78765 files scanned/usr/lib/python2.7/dist-packages/PIL/TiffImagePlugin.py:742: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0.
  warnings.warn(str(msg))
Traceback (most recent call last):
  File "/usr/local/bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 36, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 460, in new_func
    try: return func(*args, **kwargs)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/cli.py", line 67, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/usr/local/lib/python2.7/dist-packages/supysonic/cli.py", line 175, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/usr/local/lib/python2.7/dist-packages/supysonic/scanner.py", line 90, in scan
    Folder.select(lambda sub: sub.path.startswith(f.path)).delete(bulk = True)
  File "<auto generated wrapper of delete() function>", line 2, in delete
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 5499, in delete
    cursor = database._exec_sql(sql, arguments)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 820, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1625, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 818, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/dbapiprovider.py", line 58, in wrap_dbapi_exceptions
    except dbapi_module.IntegrityError as e: raise IntegrityError(e)
pony.orm.dbapiprovider.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by spl0k** [comment]
Hmm, I thought I got rid of this error...
Which DB backend are you using?

**Comment by gerroon** [comment]
I am using the default, I assume it is sqlite

**Comment by nermolov** [comment]
I have the same FOREIGN KEY constraint failed error

**Comment by spl0k** [comment]
Should now be fixed.
