### ISSUE TITLE
Errors with SQLite and PostgreSQL when scanning library (works with MySQL)

### ISSUE THREAD

**Issue by nermolov** [spl0k/supysonic#103]
supysonic works fine with MySQL, the following issues appear when using SQLite or PostgreSQL.

sqlite:
```
Scanning 'MyLibrary': 1 files scanned
Traceback (most recent call last):
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 261, in execute
    else: cursor.execute(sql, arguments)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "<string>", line 2, in onecmd
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 466, in new_func
    result = func(*args, **kwargs)
  File "/usr/lib64/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/cli.py", line 67, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/cli.py", line 182, in folder_scan
    scanner.finish()
  File "<string>", line 2, in finish
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 466, in new_func
    result = func(*args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/scanner.py", line 107, in finish
    self.__stats.deleted.albums = Album.prune()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/db.py", line 183, in prune
    return cls.select(lambda self: not exists(t for t in Track if t.album == self)).delete(bulk = True)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 5611, in delete
    cursor = database._exec_sql(sql, arguments)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 828, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 1646, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 826, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 58, in wrap_dbapi_exceptions
    except dbapi_module.IntegrityError as e: raise IntegrityError(e)
pony.orm.dbapiprovider.IntegrityError: FOREIGN KEY constraint failed

```

postgres:
```
Scanning 'MyLibrary': 1 files scanned
Traceback (most recent call last):
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 50, in wrap_dbapi_exceptions
    return func(provider, *args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/dbproviders/postgres.py", line 232, in execute
    else: cursor.execute(sql, arguments)
psycopg2.IntegrityError: update or delete on table "album" violates foreign key constraint "track_album_id_fkey" on table "track"
DETAIL:  Key (id)=(610050b3-9f33-4596-860c-19ad38ce86b3) is still referenced from table "track".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "<string>", line 2, in onecmd
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 466, in new_func
    result = func(*args, **kwargs)
  File "/usr/lib64/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/cli.py", line 67, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/cli.py", line 182, in folder_scan
    scanner.finish()
  File "<string>", line 2, in finish
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 466, in new_func
    result = func(*args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/scanner.py", line 107, in finish
    self.__stats.deleted.albums = Album.prune()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/db.py", line 183, in prune
    return cls.select(lambda self: not exists(t for t in Track if t.album == self)).delete(bulk = True)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 5611, in delete
    cursor = database._exec_sql(sql, arguments)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 828, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 1646, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 826, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 58, in wrap_dbapi_exceptions
    except dbapi_module.IntegrityError as e: raise IntegrityError(e)
pony.orm.dbapiprovider.IntegrityError: update or delete on table "album" violates foreign key constraint "track_album_id_fkey" on table "track"
DETAIL:  Key (id)=(610050b3-9f33-4596-860c-19ad38ce86b3) is still referenced from table "track".
```

**Comment by spl0k** [comment]
This seems to happen since pony 0.7.4. You can either use MySQL (if you say it works) or install pony 0.7.3 while I work this out.
```
$ pip install pony==0.7.3
```
