### ISSUE TITLE
Attempting to access album information causes an error

### ISSUE THREAD

**Issue by nermolov** [spl0k/supysonic#104]
Latest master
```
Traceback (most recent call last):
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 37, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 479, in new_func
    reraise(exc_type, exc, tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 466, in new_func
    result = func(*args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/api/browse.py", line 89, in show_directory
    child = [ f.as_subsonic_child(request.user) for f in res.children.order_by(lambda c: c.name.lower()) ] + [ t.as_subsonic_child(request.user, request.client) for t in sorted(res.tracks, key = lambda t: t.sort_key()) ]
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/api/browse.py", line 89, in <lambda>
    child = [ f.as_subsonic_child(request.user) for f in res.children.order_by(lambda c: c.name.lower()) ] + [ t.as_subsonic_child(request.user, request.client) for t in sorted(res.tracks, key = lambda t: t.sort_key()) ]
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/db.py", line 278, in sort_key
    return (self.album.artist.name + self.album.name + ("%02i" % self.disc) + ("%02i" % self.number) + self.title).lower()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 2124, in __get__
    value = attr.get(obj)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 2134, in get
    val = vals[attr] if attr in vals else attr.load(obj)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 2118, in load
    else: obj._load_()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 4460, in _load_
    'Phantom object %s disappeared' % safe_repr(obj))
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.UnrepeatableReadError: Phantom object Album[UUID('ae26079b-bbe8-48e3-92dc-550b89d565d4')] disappeared
192.168.1.227 - - [25/Jul/2018 16:59:03] "GET /rest/getMusicDirectory.view?u=nik&p=enc:6e696b&v=1.2.0&c=DSub&id=d9ff49a6-00a6-4790-af91-e74c304cd645 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 37, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 479, in new_func
    reraise(exc_type, exc, tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 466, in new_func
    result = func(*args, **kwargs)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/api/browse.py", line 89, in show_directory
    child = [ f.as_subsonic_child(request.user) for f in res.children.order_by(lambda c: c.name.lower()) ] + [ t.as_subsonic_child(request.user, request.client) for t in sorted(res.tracks, key = lambda t: t.sort_key()) ]
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/api/browse.py", line 89, in <lambda>
    child = [ f.as_subsonic_child(request.user) for f in res.children.order_by(lambda c: c.name.lower()) ] + [ t.as_subsonic_child(request.user, request.client) for t in sorted(res.tracks, key = lambda t: t.sort_key()) ]
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/supysonic/db.py", line 278, in sort_key
    return (self.album.artist.name + self.album.name + ("%02i" % self.disc) + ("%02i" % self.number) + self.title).lower()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 2124, in __get__
    value = attr.get(obj)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 2134, in get
    val = vals[attr] if attr in vals else attr.load(obj)
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 2118, in load
    else: obj._load_()
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/orm/core.py", line 4460, in _load_
    'Phantom object %s disappeared' % safe_repr(obj))
  File "/home/nik/playground/supysonic/lib/python3.6/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
```

**Comment by nermolov** [comment]
This is after a successful library scan, attempted to use DSub

**Comment by spl0k** [comment]
I wasn't able to reproduce. Could you update your supysonic installation, rescan your library (since you had issues that should now be fixed) and try to access that album info that caused this error please?
If that still happens, does it happen for every album or just some? In the latter case, is there some missing tags in files of that album?
