### ISSUE TITLE
I cant stay logged in

### ISSUE THREAD

**Issue by gerroon** [spl0k/supysonic#113]
Hi

I set this up using virtualenv on Debian Testing Py 2.7, Apache/2.4.34, Wsgi

Everything seems to work like accessing, scanning, Dsub as a client etc except one issue. The web page constantly logs me out almost every 10 seconds, I login back it works a bit then I am out.

One operation that kicks me out is trying to set Dsub with transcoding. The second I press save, I am out again.

Any recommendation?

**Comment by spl0k** [comment]
Hi.
Are you using Apache with `mod_wsgi` or as a reverse proxy? Could you please post the relevant configuration?

**Comment by gerroon** [comment]
I tried to mention in the post aboive, it is wsgi. I am using the given wsgi config except that I had to modify one line since it was not working with apache2 version

```
WSGIScriptAlias /supysonic /media/DRIVE/var/www/SupySonic/cgi-bin/supysonic.wsgi
        <Directory /media/DRIVE/var/www/SupySonic/cgi-bin>
            WSGIApplicationGroup %{GLOBAL}
            WSGIPassAuthorization On
            Require all granted
            #Order deny,allow
            Allow from all
        </Directory>

```

**Comment by spl0k** [comment]
It should now be fixed, thanks.

**Comment by gerroon** [comment]
Actually this semeed to introduce something new, no sure if it is the same thing

```

[Sat Sep 08 13:06:02.018217 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140] [2018-09-08 13:06:02,017] ERROR in app: Exception on /user/me [POST], referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018239 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140] Traceback (most recent call last):, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018245 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018250 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     response = self.full_dispatch_request(), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018254 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018259 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     rv = self.handle_user_exception(e), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018263 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018268 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     reraise(exc_type, exc_value, tb), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018272 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018277 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     rv = self.dispatch_request(), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018281 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018286 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     return self.view_functions[rule.endpoint](**req.view_args), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018290 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/frontend/user.py", line 49, in decorated_func, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018295 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     return f(*args, **kwargs), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018299 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/frontend/user.py", line 92, in update_clients, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018304 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     prefs.format  =     opts['format']   if 'format'  in opts and opts['format']  else None, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018316 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 2184, in __set__, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018321 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     new_val = attr.validate(new_val, obj, from_db=False), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018325 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 2090, in validate, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018330 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     val = converter.validate(val, obj), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018334 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 450, in validate, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018338 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     % (converter.attr, max_len, val_len)), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018342 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/SYSLINX/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/utils/utils.py", line 106, in throw, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018347 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     raise exc, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018351 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140] ValueError: Value for attribute ClientPrefs.format is too long. Max length is 8, value length is 16, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me


```
