### ISSUE TITLE
ValueError: Value for attribute ClientPrefs.format is too long

### ISSUE THREAD

**Issue by gerroon** [spl0k/supysonic#115]
I just pulled, and updated my local instance and this is what I am getting when trying to save transcoding for Dsub

Using Debian testing, Apache/2.4.34, wsgi, Virtualenv, py2.7. 

I also need to add this line to wsgi since it is under virtualenv 

```
activate_this='/media/DRIVE/var/www/SupySonic/SupySonic/bin/activate_this.py'                                                                                                               
execfile(activate_this, dict(__file__=activate_this))    
```

```

[Sat Sep 08 13:06:02.018217 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140] [2018-09-08 13:06:02,017] ERROR in app: Exception on /user/me [POST], referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018239 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140] Traceback (most recent call last):, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018245 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018250 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     response = self.full_dispatch_request(), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018254 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018259 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     rv = self.handle_user_exception(e), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018263 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018268 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     reraise(exc_type, exc_value, tb), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018272 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018277 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     rv = self.dispatch_request(), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018281 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018286 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     return self.view_functions[rule.endpoint](**req.view_args), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018290 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/frontend/user.py", line 49, in decorated_func, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018295 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     return f(*args, **kwargs), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018299 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/frontend/user.py", line 92, in update_clients, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018304 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     prefs.format  =     opts['format']   if 'format'  in opts and opts['format']  else None, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018316 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 2184, in __set__, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018321 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     new_val = attr.validate(new_val, obj, from_db=False), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018325 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 2090, in validate, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018330 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     val = converter.validate(val, obj), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018334 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 450, in validate, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018338 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     % (converter.attr, max_len, val_len)), referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018342 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/utils/utils.py", line 106, in throw, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018347 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140]     raise exc, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me
[Sat Sep 08 13:06:02.018351 2018] [wsgi:error] [pid 22837] [client 192.168.5.113:34140] ValueError: Value for attribute ClientPrefs.format is too long. Max length is 8, value length is 16, referer: https://DOMAIN.DOMAIN.org/supysonic/user/me


```

**Comment by gerroon** [comment]
Btw I get the exact same error for the same operation with the python server

**Comment by spl0k** [comment]
Ok, maybe these fields lack some documentation (and validation). You're supposed to put only one format here: the one you want any track to be converted to.

Those two lines you added for the virtualenv aren't necessary. `mod_wsgi` supports virtual environments, you just have to add a few directives to the apache configuration.
https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html
The sample given in supysonic's README is the _embedded mode_, but you might want to try the _daemon mode_ if you have other WSGI apps.

**Comment by gerroon** [comment]
So I can only transcode  single format? I would like to transcode anything bigger than 192lb (for my mobile.)

I will look into the wsgi methods. The current solution works for me, I did not know about fixing it on the apache side.

**Comment by spl0k** [comment]
You can only transcode **to** a single format. Say you have mp3, ogg and flac files in your library and you put _mp3_ in the _format_ box; all your files, whether it be mp3, ogg or flac, will be converted to mp3.
But the value you put in that field is only a hint for the server if the client doesn't specify which format to convert to (DSub doesn't seem to offer a setting where you can choose the format).
Note that you can leave the format field empty and only choose a bitrate. This way mp3 files will be served as mp3, ogg as ogg, etc. They'll only be transcoded to this bitrate if it is lower than the original files'.

**Comment by gerroon** [comment]
@spl0k  thanks for the help. Maybe this can be added to the wiki.

thnx
