### ISSUE TITLE
Exception when you use new unregistered client

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#117]
Simply delete your existing _Jamstash_ client and use it again. The log throws this:

```
Exception on /rest/getPlaylists.view [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/supysonic-0.3-py3.7.egg/supysonic/api/playlists.py", line 35, in list_playlists
    return request.formatter('playlists', dict(playlist = [ p.as_subsonic_playlist(request.user) for p in query ] ))
  File "/usr/local/lib/python3.7/site-packages/supysonic-0.3-py3.7.egg/supysonic/api/playlists.py", line 35, in <listcomp>
    return request.formatter('playlists', dict(playlist = [ p.as_subsonic_playlist(request.user) for p in query ] ))
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5958, in next
    qr._items = qr._query._actual_fetch(qr._limit, qr._offset)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5499, in _actual_fetch
    cache.prepare_connection_for_query_execution()  # may clear cache.query_results
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 1712, in prepare_connection_for_query_execution
    if not cache.noflush_counter and cache.modified: cache.flush()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 1797, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5090, in _save_
    if status == 'created': obj._save_created_()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 4934, in _save_created_
    % (obj, e.__class__.__name__, msg), e)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.TransactionIntegrityError: Object ClientPrefs[User[UUID('d7f7039e-5443-4377-b3b8-d7865079d809')],'Jamstash'] cannot be stored in the database. IntegrityError: UNIQUE constraint failed: client_prefs.user_id, client_prefs.client_name
Exception on /rest/getIndexes.view [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/supysonic-0.3-py3.7.egg/supysonic/api/browse.py", line 38, in list_indexes
    folders = Folder.select(lambda f: f.root)[:]
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5860, in __getitem__
    return query._fetch()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5867, in _fetch
    return QueryResult(query, limit, offset, lazy=lazy)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5981, in __init__
    self._items = None if lazy else self._query._actual_fetch(limit, offset)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5499, in _actual_fetch
    cache.prepare_connection_for_query_execution()  # may clear cache.query_results
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 1712, in prepare_connection_for_query_execution
    if not cache.noflush_counter and cache.modified: cache.flush()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 1797, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 5090, in _save_
    if status == 'created': obj._save_created_()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/orm/core.py", line 4934, in _save_created_
    % (obj, e.__class__.__name__, msg), e)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.6-py3.7.egg/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.TransactionIntegrityError: Object ClientPrefs[User[UUID('d7f7039e-5443-4377-b3b8-d7865079d809')],'Jamstash'] cannot be stored in the database. IntegrityError: UNIQUE constraint failed: client_prefs.user_id, client_prefs.client_name
```

Maybe is calling to create function more than once?

**Comment by apastuszak** [comment]
Having the same issue now.

Using PostgreSQL
