### ISSUE TITLE
pony.orm.dbapiprovider.OperationalError: no such column: has_art

### ISSUE THREAD

**Issue by gerroon** [spl0k/supysonic#125]
I just upgraded today using git pull then pip install .

```
supysonic-cli folder scan Music
Scanning 'Music': 18862 files scannedTraceback (most recent call last):
  File "/media/DRIVE/opt/SupySonic/SupySonic/bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/utils/utils.py", line 37, in pony_wrapper                                                              
    return caller(func, *args, **kwargs)
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 467, in new_func                                                                    
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/supysonic/cli.py", line 67, in method                                                                       
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/supysonic/cli.py", line 175, in folder_scan                                                                 
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/supysonic/scanner.py", line 73, in scan                                                                     
    self.scan_file(full_path)
  File "<auto generated wrapper of scan_file() function>", line 2, in scan_file
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python3.7/site-packages/pony/orm/core.py", line 468, in new_func                                                                    
    commit()
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 337, in commit                                                                      
    rollback_and_reraise(sys.exc_info())
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 326, in rollback_and_reraise                                                        
    reraise(*exc_info)
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 335, in commit                                                                      
    cache.flush()
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 1797, in flush                                                                      
    if obj is not None: obj._save_()
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 5091, in _save_                                                                     
    elif status == 'modified': obj._save_updated_()
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 5000, in _save_updated_                                                             
    cursor = database._exec_sql(sql, arguments, start_transaction=True)
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 863, in _exec_sql                                                                   
    connection = cache.reconnect(e)
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 1686, in reconnect                                                                  
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/core.py", line 861, in _exec_sql                                                                   
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/media/DRIVE/opt/SupySonic/SupySonic/local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 61, in wrap_dbapi_exceptions                                               
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such column: has_art
```

**Comment by spl0k** [comment]
Your previous installation didn't feature the automatic migration system, and the database schema changed in the meantime.
You'll have to manually apply the last migration script. It is _20181010.sql_ located in _supysonic/schema/migration/YOUR DB BACKEND/_

**Comment by gerroon** [comment]
How do I apply it? Sorry I am do not know much about this stuff.

**Comment by spl0k** [comment]
Here are the commands for the three supported database backends. Those are assuming you're in the folder where you cloned the repository. Replace the parameters to match your configuration.

If you're using SQLite:
```
$ sqlite3 /path/to/your/supysonic.db < supysonic/schema/migration/sqlite/20181010.sql
```
For MySQL / MariaDB:
```
$ mysql -u YourDbUser -p YourDbName < supysonic/schema/migration/mysql/20181010.sql
```
For PostgreSQL:
```
$ psql -h localhost -d YourDbName -U YourDbUser < supysonic/schema/migration/postgres/20181010.sql
```

**Comment by gerroon** [comment]
Nevermind I waited long enough sure enough it proceeded properly.
