### ISSUE TITLE
Wsgi ERROR in app: Exception on /folder/scan

### ISSUE THREAD

**Issue by gerroon** [spl0k/supysonic#126]
Hi

Whenever I try to search in the folders section using the magnifying glass icon, I get "Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

And I get the log below in error.log  

I am using the Virtenv method to install Supysonic, and using wsgi un Apache. Everything seems to work except this particular use case.

It says sdatabase locked, but it cant be because no other client is connected.

```
[Mon Oct 29 13:12:04.511926 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982] [2018-10-29 13:12:04,509] ERROR in app: Exception on /folder/scan/c4b7bf7a-9457-421b-8a52-5686a5e64c30 [GET], referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 30 13:12:04.511951 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982] Traceback (most recent call last):, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511955 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511960 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     response = self.full_dispatch_request(), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511964 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511968 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     rv = self.handle_user_exception(e), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511972 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511976 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     reraise(exc_type, exc_value, tb), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511980 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511984 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     rv = self.dispatch_request(), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511987 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511992 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     return self.view_functions[rule.endpoint](**req.view_args), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.511996 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/frontend/__init__.py", line 51, in decorated_func, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512000 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     return f(*args, **kwargs), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512004 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/frontend/folder.py", line 91, in scan_folder, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512008 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     scanner.scan(folder), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512011 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/scanner.py", line 73, in scan, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512023 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     self.scan_file(full_path), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512028 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "<auto generated wrapper of scan_file() function>", line 2, in scan_file, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512032 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 467, in new_func, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512036 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     result = func(*args, **kwargs), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512040 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/scanner.py", line 116, in scan_file, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512044 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     tr = Track.get(path = path), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512048 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/supysonic/db.py", line 60, in get, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512052 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     return db.Entity.get.__func__(cls, *args, **kwargs), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512055 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 3768, in get, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512059 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512063 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 3867, in _find_one_, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512068 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     if obj is None: obj = entity._find_in_db_(avdict, unique, for_update, nowait), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512071 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 3926, in _find_in_db_, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512076 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     cursor = database._exec_sql(sql, arguments), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512079 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 856, in _exec_sql, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512084 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     connection = cache.prepare_connection_for_query_execution(), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512087 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 1711, in prepare_connection_for_query_execution, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512094 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     except Exception as e: connection = cache.reconnect(e), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512098 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 1686, in reconnect, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512103 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     if not provider.should_reconnect(exc): reraise(*sys.exc_info()), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512107 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/core.py", line 1710, in prepare_connection_for_query_execution, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512111 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     try: provider.set_transaction_mode(connection, cache)  # can set cache.in_transaction, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512115 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "<auto generated wrapper of set_transaction_mode() function>", line 2, in set_transaction_mode, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512119 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]   File "/media/DRIVE/var/www/SupySonic/SupySonic/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 61, in wrap_dbapi_exceptions, referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512123 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982]     raise OperationalError(e), referer: https://XXXX.XXX.org/supysonic/folder
[Mon Oct 29 13:12:04.512127 2018] [wsgi:error] [pid 16349] [client 192.168.1.100:55982] OperationalError: database is locked, referer: https://XXXX.XXX.org/supysonic/folder

```

**Comment by spl0k** [comment]
I already ran into this issue, but I can't remember the context or how I fixed it.
Do you have the watcher running at the same time? Or maybe the CLI?

**Comment by gerroon** [comment]
I was only running the web ui, no other clients

**Comment by spl0k** [comment]
Triaging and closing old issues. Don't hesitate to reopen if you feel this still need to be investigated.
