### ISSUE TITLE
ExpatError: not well-formed (invalid token) when handling null bytes

### ISSUE THREAD

**Issue by mremallin** [spl0k/supysonic#133]
Release: 7cfd958eebee432c2f99419393b9aac525972f69

Issue: Traceback when attempting to load my library.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pony-0.7.6-py2.7.egg/pony/utils/utils.py", line 37, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony-0.7.6-py2.7.egg/pony/orm/core.py", line 467, in new_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-1.0.2-py2.7.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/api/albums_songs.py", line 113, in album_list_id3
    album = [ f.as_subsonic_album(request.user) for f in query.limit(size, offset) ]
  File "/usr/local/lib/python2.7/dist-packages/supysonic/api/formatters.py", line 28, in __call__
    return self.make_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supysonic/api/formatters.py", line 141, in make_response
    rv = minidom.parseString(ElementTree.tostring(root)).toprettyxml(indent = '  ')
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: not well-formed (invalid token): line 1, column 1583
```

The response has the following album which is in column 1583:

`<album artist="Roberta Flack\x00" artistId="d6d34d3a-ba02-44e4-87df-50947a61919b" coverArt="2139e33e-7988-4114-9fd7-922218bfa6d9" created="2019-01-16T01:25:55" duration="2460" id="d01a3cb1-dbc2-48d0-8660-1af8275477d5" name="Killing Me Softly\x00" songCount="8" />`

It seems like the XML builder doesn't properly escape the null bytes in the strings. (https://github.com/spl0k/supysonic/blob/master/supysonic/api/formatters.py#L117)

I think it'd make sense to strip out null bytes in the string, but what about other non-ascii characters? Would it be best to escape everything and let the clients deal with it?

**Comment by pR0Ps** [comment]
FYI some tag stripping is already done on import in this function: https://github.com/spl0k/supysonic/blob/7cfd958eebee432c2f99419393b9aac525972f69/supysonic/scanner.py#L302

Maybe strip out trailing null bytes with something like `value = [x.rstrip('\x00') for x in value]` right before the `if transform:` line*? That isn't enough to solve the "bad XML" issue in the general case though...

*Sidenote: Looking at it now, I think the `return value if value else default` just under that line should be unindented 1 level

**Comment by mremallin** [comment]
#134
