### ISSUE TITLE
ValueError: Attribute Folder.name is required

### ISSUE THREAD

**Issue by freezoo2** [spl0k/supysonic#148]
Hi,

Just installed masted with all dependencies and getting following error while scanning (after scanning 800 files):

```
root@9fe43abe8390:/# supysonic-cli folder scan
Scanning 'audio': 689 files scannedTraceback (most recent call last):
  File "/usr/local/bin/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "<string>", line 2, in onecmd
  File "/usr/local/lib/python3.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.7/site-packages/supysonic/cli.py", line 66, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/usr/local/lib/python3.7/site-packages/supysonic/cli.py", line 178, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/usr/local/lib/python3.7/site-packages/supysonic/scanner.py", line 74, in scan
    self.scan_file(full_path)
  File "<string>", line 2, in scan_file
  File "/usr/local/lib/python3.7/site-packages/pony/orm/core.py", line 515, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/supysonic/scanner.py", line 156, in scan_file
    trdict['folder'] = self.__find_folder(path)
  File "/usr/local/lib/python3.7/site-packages/supysonic/scanner.py", line 296, in __find_folder
    folder = Folder(parent = folder, **children.pop())
  File "/usr/local/lib/python3.7/site-packages/supysonic/db.py", line 65, in __init__
    db.Entity.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pony/orm/core.py", line 4642, in __init__
    avdict[attr] = attr.validate(val, obj, entity, from_db=False)
  File "/usr/local/lib/python3.7/site-packages/pony/orm/core.py", line 2514, in validate
    attr if obj is None or obj._status_ is None else '%r.%s' % (obj, attr.name)))
  File "/usr/local/lib/python3.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
ValueError: Attribute Folder.name is required
```

So it looks like there is something wrong with one file being scanned.

**Comment by freezoo2** [comment]
The problem is coming from one specific file in my library.  For some reason I had a file in a path like this:
/media/album/ /filename.mp3

There was a folder which name was a single whitespace.

I deleted this file/folder and now it is working fine
