### ISSUE TITLE
IntegrityError: FOREIGN KEY constraint failed migrating from SQLite schema 20181010 to latest one

### ISSUE THREAD

**Issue by ogarcia** [spl0k/supysonic#151]
I have running a server with code from commit `5367f068e1ac826cfd5354b5b76818ba4b259ac2` and today I updated it to latest commit and I have the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/dbapiprovider.py", line 263, in execute
    if arguments is None: cursor.execute(sql)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/supysonic.fcgi", line 3, in <module>
    app = create_application()
  File "/usr/local/lib/python3.7/site-packages/supysonic-0.3-py3.7.egg/supysonic/web.py", line 50, in create_application
    init_database(app.config['BASE']['database_uri'])
  File "/usr/local/lib/python3.7/site-packages/supysonic-0.3-py3.7.egg/supysonic/db.py", line 577, in init_database
    execute_sql_resource_script('schema/migration/{}/{}'.format(settings['provider'], migration))
  File "/usr/local/lib/python3.7/site-packages/supysonic-0.3-py3.7.egg/supysonic/db.py", line 551, in execute_sql_resource_script
    metadb.execute(statement)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 870, in execute
    return database._exec_raw_sql(sql, globals, locals, frame_depth=cut_traceback_depth+1, start_transaction=True)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 882, in _exec_raw_sql
    return database._exec_sql(adapted_sql, arguments, False, start_transaction)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 945, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 1776, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 943, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/dbapiprovider.py", line 58, in wrap_dbapi_exceptions
    except dbapi_module.IntegrityError as e: raise IntegrityError(e)
pony.orm.dbapiprovider.IntegrityError: FOREIGN KEY constraint failed
```

If I apply changes from `20190324.sql` and `20190518.sql` by hand and update the `schema_version` in database running `update meta SET value='20190518' WHERE key='schema_version';` it seems work all ok.

I have a backup of database to make tests if you need it.

Nope. Seems work, but when you ask for a song you have following error:
```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/dbapiprovider.py", line 264, in execute
    else: cursor.execute(sql, arguments)
sqlite3.OperationalError: no such table: main.track_old

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Flask-1.0.3-py3.7.egg/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/utils/utils.py", line 37, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 529, in new_func
    commit()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 381, in commit
    rollback_and_reraise(sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 370, in rollback_and_reraise
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 379, in commit
    cache.flush()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 1888, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 5363, in _save_
    elif status == 'modified': obj._save_updated_()
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 5272, in _save_updated_
    cursor = database._exec_sql(sql, arguments, start_transaction=True)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 945, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 1776, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/core.py", line 943, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
    from pony.py23compat import PY2, basestring, unicode, buffer, int_types, iteritems
  File "/usr/local/lib/python3.7/site-packages/pony-0.7.10-py3.7.egg/pony/orm/dbapiprovider.py", line 61, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such table: main.track_old
```

**Comment by ogarcia** [comment]
More info. Looking into database I can see at least two references to track_old:
```
sqlite> .schema starred_track
CREATE TABLE starred_track (
	user_id CHAR(36) NOT NULL REFERENCES user,
	starred_id CHAR(36) NOT NULL REFERENCES "track_old",
	date DATETIME NOT NULL,
	PRIMARY KEY (user_id, starred_id)
);
CREATE INDEX index_starred_track_user_id_fk ON starred_track(user_id);
CREATE INDEX index_starred_track_starred_id_fk ON starred_track(starred_id);
sqlite> .schema user
CREATE TABLE user (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	mail VARCHAR(256),
	password CHAR(40) NOT NULL,
	salt CHAR(6) NOT NULL,
	admin BOOLEAN NOT NULL,
	lastfm_session CHAR(32),
	lastfm_status BOOLEAN NOT NULL,
	last_play_id CHAR(36) REFERENCES "track_old",
	last_play_date DATETIME
);
CREATE INDEX index_user_last_play_id_fk ON user(last_play_id);
```

Seems that the rename move the relations in database.

**Comment by ogarcia** [comment]
I think that problem is in SQLite migration `20190518.sql`. You do the following:
1. Rename old table
2. Create new table
3. Copy data
4. Drop old table

But this is wrong because the relations are renamed too. You must do:
1. Create a new table
2. Copy data
3. Drop old table
4. Rename new into old

And it works like a charm

The sql file that works for me:
```
DROP INDEX index_track_album_id_fk;
DROP INDEX index_track_artist_id_fk;
DROP INDEX index_track_folder_id_fk;
DROP INDEX index_track_root_folder_id_fk;
DROP INDEX index_track_path;

CREATE TABLE IF NOT EXISTS track_new (
    id CHAR(36) PRIMARY KEY,
    disc INTEGER NOT NULL,
    number INTEGER NOT NULL,
    title VARCHAR(256) NOT NULL COLLATE NOCASE,
    year INTEGER,
    genre VARCHAR(256),
    duration INTEGER NOT NULL,
    has_art BOOLEAN NOT NULL DEFAULT false,
    album_id CHAR(36) NOT NULL REFERENCES album,
    artist_id CHAR(36) NOT NULL REFERENCES artist,
    bitrate INTEGER NOT NULL,
    path VARCHAR(4096) NOT NULL,
    path_hash BLOB NOT NULL,
    created DATETIME NOT NULL,
    last_modification INTEGER NOT NULL,
    play_count INTEGER NOT NULL,
    last_play DATETIME,
    root_folder_id CHAR(36) NOT NULL REFERENCES folder,
    folder_id CHAR(36) NOT NULL REFERENCES folder
);

CREATE INDEX IF NOT EXISTS index_track_album_id_fk ON track_new(album_id);
CREATE INDEX IF NOT EXISTS index_track_artist_id_fk ON track_new(artist_id);
CREATE INDEX IF NOT EXISTS index_track_folder_id_fk ON track_new(folder_id);
CREATE INDEX IF NOT EXISTS index_track_root_folder_id_fk ON track_new(root_folder_id);
CREATE UNIQUE INDEX IF NOT EXISTS index_track_path ON track_new(path_hash);

INSERT INTO track_new(id, disc, number, title, year, genre, duration, has_art, album_id, artist_id, bitrate, path, path_hash, created, last_modification, play_count, last_play, root_folder_id, folder_id)
SELECT id, disc, number, title, year, genre, duration, has_art, album_id, artist_id, bitrate, path, path_hash, created, last_modification, play_count, last_play, root_folder_id, folder_id
FROM track;

DROP TABLE track;

ALTER TABLE track_new RENAME TO track;

VACUUM;
```

**Comment by spl0k** [comment]
Thank you for your report and investigation.

Actually your solution still has issues. If you run your script with the `sqlite3` command you'll have no issue since foreign keys aren't enforced by default, which isn't the case within Supysonic's context. You have to add a `PRAGMA foreign_keys = OFF;` at the beginning and reenable them at the end with `PRAGMA foreign_keys = ON;`.
But there's still a catch: those can't be run within a transaction and a transaction is started before running migrations. So we have to `COMMIT` before disabling foreign keys, start a new transaction, execute the actual migration, `COMMIT` and reenable foreign keys. `VACUUM` also has to be run outside of a transaction.
