### ISSUE TITLE
Error in Centos 7 with SQLite

### ISSUE THREAD

**Issue by dougbrose** [spl0k/supysonic#160]
Hi Supysonic,

I followed these guidelines on CentOS 7 and I get an error when trying to start the server.py in the cgi directory (or use the cli).  Has anyone run into this.

Guidelines
https://whatbox.ca/wiki/Supysonic

Thank you,

```
Traceback (most recent call last):
  File "/usr/bin/supysonic-cli", line 11, in <module>
    load_entry_point('supysonic==0.4', 'console_scripts', 'supysonic-cli')()
  File "/usr/lib/python2.7/site-packages/supysonic-0.4-py2.7.egg/supysonic/cli.py", line 404, in main
    init_database(config.BASE["database_uri"])
  File "/usr/lib/python2.7/site-packages/supysonic-0.4-py2.7.egg/supysonic/db.py", line 621, in init_database
    version = Meta["schema_version"]
  File "/usr/lib/python2.7/site-packages/pony-0.7.10-py2.7.egg/pony/orm/core.py", line 3939, in __getitem__
    return entity._find_one_(kwargs)
  File "/usr/lib/python2.7/site-packages/pony-0.7.10-py2.7.egg/pony/orm/core.py", line 4059, in _find_one_
    if obj is None: throw(ObjectNotFound, entity, pkval)
  File "/usr/lib/python2.7/site-packages/pony-0.7.10-py2.7.egg/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.ObjectNotFound: Meta[u'schema_version']
```

**Comment by spl0k** [comment]
Hello,

This guide is a bit outdated. What is causing the issue here is that you created the database directly from the SQL scripts when it's supposed to be done automatically if needed.
You can work around the error by deleting the file `~/.config/supysonic/library.db` and skipping the 8th step of the guide.

If this guide would be rewritten (poke @shuddertrix), steps 3 to 5 could be simplified as
>3. Download the latest supysonic release
>```
>git clone https://github.com/spl0k/supysonic.git
>cd supysonic
>```
>4. With your virtualenv activated, install supysonic and all its dependencies
>```
>pip install .
>```

Step 7 has a typo, it's `cache_dir` and not `cache-dir`. Skip step 8, in step 9 add a `folder scan files` before `exit` as you now can't run a scan from the web UI (step 11) if the daemon service isn't started. The rest should be ok.

**Comment by dougbrose** [comment]
That worked perfect thank you.  I had to add

`pip install uwsgi`

But then everything started right up.
