### ISSUE TITLE
supysonic refuses to take off.

### ISSUE THREAD

**Issue by hboetes** [spl0k/supysonic#193]
So I followed all instructions, installed all dependencies, set up a config-file and db, which I can connect to as the supysonic user with the right password, the initial tables are there, and then I run the standalone server for testing purposes and I get this output:
```
% /var/www/cgi-bin/supysonic/server.py   
Traceback (most recent call last):
  File "/var/www/cgi-bin/supysonic/server.py", line 12, in <module>
    app = create_application()
  File "/usr/local/lib/python3.7/site-packages/supysonic/web.py", line 54, in create_application
    init_database(app.config["BASE"]["database_uri"])
  File "/usr/local/lib/python3.7/site-packages/supysonic/db.py", line 639, in init_database
    version = Meta["schema_version"]
  File "/usr/local/lib/python3.7/site-packages/pony/orm/core.py", line 3995, in __getitem__
    return entity._find_one_(kwargs)
  File "/usr/local/lib/python3.7/site-packages/pony/orm/core.py", line 4119, in _find_one_
    if obj is None: throw(ObjectNotFound, entity, pkval)
  File "/usr/local/lib/python3.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.ObjectNotFound: Meta['schema_version']
```

What am I missing here?

**Comment by spl0k** [comment]
So I guess you managed to solve the issue by yourself since you closed this. What was the problem? How did you fix it?

**Comment by hboetes** [comment]
No I gave up on supysonic because I ran in too many issues.

**Comment by spl0k** [comment]
I'm sorry to hear this. Care to share the issues you faced?

**Comment by hboetes** [comment]
There were quite a few, one of them was that OpenBSD has a rather restricted set of open files, which I had to increase a lot before supysonic started running. And a few more issues, I can't quite remember them all.

Best of luck making supysonic a great project, maybe I'll check again in a few months.
