### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by trap000d** [spl0k/supysonic#241]
Environment: Arch Linux
Version: 0.7.3-1 (AUR)
Python: 3.10
PostgreSQL: postgresql 14.6-1

After upgrading of supysonic to 0.7.3.-1 it stops working. Web frontend only throws error 500, so I had to look through logs and command line. 

In brief, the problem looks like Postgres types mismatch (UUID won't cast to BYTEA in table 'user').

For example, I'm getting the following error with supysonic-cli:

```Python
[supysonic@me ~]$ supysonic-cli user add newuser
Password:
Repeat for confirmation:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.DatatypeMismatch: column "id" is of type uuid but expression is of type bytea
LINE 1: ...lt", "admin", "jukebox", "lastfm_status") VALUES ('\x915fa92...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/supysonic-cli", line 33, in <module>
    sys.exit(load_entry_point('Supysonic==0.7.3', 'console_scripts', 'supysonic-cli')())
  File "/usr/lib/python3.10/site-packages/supysonic/cli.py", line 367, in main
    cli.main(obj=config)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/supysonic/cli.py", line 260, in user_add
    UserManager.add(name, password, mail=email)
  File "/usr/lib/python3.10/site-packages/supysonic/managers/user.py", line 35, in add
    return User.create(name=name, password=crypt, salt=salt, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6532, in create
    inst.save(force_insert=True)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6742, in save
    pk = self.insert(**field_dict).execute()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2838, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2549, in _execute
    cursor = self.execute_returning(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2556, in execute_returning
    cursor = database.execute(self)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: column "id" is of type uuid but expression is of type bytea
LINE 1: ...lt", "admin", "jukebox", "lastfm_status") VALUES ('\x915fa92...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
```
The same happens at any call to Postgres either via web or command line, so I just don't want flooding the issue with extra logs

**Comment by spl0k** [comment]
Obviously, the DBMS I don't test is the one that breaks 😐
I'll try to fix it ASAP. In the meantime you can revert to the 0.7.2 version

Thank you for the report.

**Comment by trap000d** [comment]
Well... It crashes now in other place:
1. Here is Postgres error:
```
Jan 15 14:25:00 [hostname] postgres[1247966]: 2023-01-15 14:25:00.337 NZDT [1247966] ERROR:  count(*) must be used to call a parameterless aggregate function at character 22
Jan 15 14:25:00 [hostname] postgres[1247966]: 2023-01-15 14:25:00.337 NZDT [1247966] STATEMENT:  SELECT "t1"."genre", count(), count(DISTINCT "t1"."album_id") FROM "track" AS "t1" GROUP BY "t1"."genre"
Jan 15 14:25:00 [hostname] postgres[1247966]: 2023-01-15 14:25:00.338 NZDT [1247966] ERROR:  current transaction is aborted, commands ignored until end of transaction block
Jan 15 14:25:00 [hostname] postgres[1247966]: 2023-01-15 14:25:00.338 NZDT [1247966] STATEMENT:  BEGIN
``` 

The corresponding code I guess is here - L:142:supysonic/api/browse.py:
```Python
@api_routing("/getGenres")
def list_genres():
    return request.formatter(
        "genres",
        {
            "genre": [
                {"value": genre, "songCount": sc, "albumCount": ac}
                for genre, sc, ac in Track.select(
                    Track.genre, fn.count(), fn.count(Track.album.distinct())
                )
                .group_by(Track.genre)
                .tuples()
            ]
        },
    )
```

Supysonic server throws the following exceptions:

(here they mentioned 'psycopg2.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq' is a known gunicorn multi-thread issue - https://github.com/psycopg/psycopg2/issues/281#issuecomment-985387977 , however according to gunicorn documentation, "preload_app = False" is set by default, so it's a mystery to me. I suspect it might be e.g. stale Postgres connection left after gunicorn restart)
 
```Python
2023-01-15 14:25:00,291 [ERROR] Exception on /rest/getMusicFolders.view [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1818, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2309, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/lib/python3.10/site-packages/supysonic/api/__init__.py", line 72, in authorize
    user = UserManager.try_auth(username, password)
  File "/usr/lib/python3.10/site-packages/supysonic/managers/user.py", line 49, in try_auth
    user = User.get_or_none(name=name)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6629, in get_or_none
    return cls.get(*query, **filters)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6624, in get
    return sq.get()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.10/site-packages/peewee.py", line 4435, in __getitem__
    self.fill_cache(item if item > 0 else 0)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 4483, in fill_cache
    iterator.next()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 4538, in next
    self.cursor_wrapper.iterate()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 4449, in iterate
    row = self.cursor.fetchone()
psycopg2.ProgrammingError: no results to fetch
2023-01-15 14:25:00,291 [ERROR] Exception on /rest/getIndexes.view [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1818, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2309, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/lib/python3.10/site-packages/supysonic/api/__init__.py", line 72, in authorize
    user = UserManager.try_auth(username, password)
  File "/usr/lib/python3.10/site-packages/supysonic/managers/user.py", line 49, in try_auth
    user = User.get_or_none(name=name)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6629, in get_or_none
    return cls.get(*query, **filters)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6624, in get
    return sq.get()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2206, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq
2023-01-15 14:25:00,320 [ERROR] Exception on /rest/getPlaylists.view [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3390, in commit
    return self._state.conn.commit()
psycopg2.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3244, in execute_sql
    self.commit()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3389, in commit
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3390, in commit
    return self._state.conn.commit()
peewee.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1818, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2309, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/lib/python3.10/site-packages/supysonic/api/__init__.py", line 72, in authorize
    user = UserManager.try_auth(username, password)
  File "/usr/lib/python3.10/site-packages/supysonic/managers/user.py", line 49, in try_auth
    user = User.get_or_none(name=name)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6629, in get_or_none
    return cls.get(*query, **filters)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6624, in get
    return sq.get()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2206, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3244, in execute_sql
    self.commit()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3389, in commit
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3390, in commit
    return self._state.conn.commit()
peewee.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq
2023-01-15 14:25:00,339 [ERROR] Exception on /rest/getGenres.view [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.WrongObjectType: count(*) must be used to call a parameterless aggregate function
LINE 1: SELECT "t1"."genre", count(), count(DISTINCT "t1"."album_id"...
                             ^
                             
                             
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/supysonic/api/browse.py", line 139, in list_genres
    "genre": [
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7062, in __iter__
    self.execute()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2206, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: count(*) must be used to call a parameterless aggregate function
LINE 1: SELECT "t1"."genre", count(), count(DISTINCT "t1"."album_id"...
                             ^
                             
2023-01-15 14:25:00,339 [ERROR] Exception on /rest/getPodcasts.view [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

                             
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1818, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2309, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/lib/python3.10/site-packages/supysonic/api/__init__.py", line 72, in authorize
    user = UserManager.try_auth(username, password)
  File "/usr/lib/python3.10/site-packages/supysonic/managers/user.py", line 49, in try_auth
    user = User.get_or_none(name=name)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6629, in get_or_none
    return cls.get(*query, **filters)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6624, in get
    return sq.get()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2206, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by trap000d** [comment]
Updates. 
There was only one place where ```fn.count()``` called without arguments, So after of adding an asterisk 
https://github.com/spl0k/supysonic/blob/09a5fb12ed54735dd72375120daf6998422b11da/supysonic/api/browse.py#L142
```Python
Track.genre, fn.count('*'), fn.count(Track.album.distinct())
```
the first error seems disappeared.

For the second error ```psycopg2.DatabaseError: error with status PGRES_TUPLES_OK and no message from the libpq```
indeed, it looks like a multi-process issue. Once I start only a single instance of gunicorn, i.e.
```
supysonic-server -h 127.0.0.1 -S gunicorn --processes 1
```
it works well without any issues. 

I'm going to give a try and start gunicorn directly (have no time right now, so later, or tomorrow), e.g.
```
gunicorn -w 4 -b 127.0.0.1:5722 --config=~/.config/gunicorn.conf.py "supysonic.web:create_application()"
```
and see if it fixes the problem.

**Comment by spl0k** [comment]
(╯°□°）╯︵ ┻━┻
I already hit that `count` issue on another project. Some people (me) never learn from their mistakes 😞

As for the other issue, `supysonic-daemon` is independent from `supysonic-server`, so it shouldn't start gunicorn; but the two of them opening a SQL connection is expected.

**Comment by trap000d** [comment]
> I already hit that `count` issue on another project. Some people (me) never learn from their mistakes
No worries, ability to forget is a gift :)
 
> As for the other issue, `supysonic-daemon` is independent from `supysonic-server`, so it shouldn't start gunicorn; but the two of them opening a SQL connection is expected.

What I've observed.
Indeed, `supysonic-daemon` instance is not related to issue.
When I start `supysonic-server`, e.g. `supysonic-server -h 127.0.0.1 -S gunicorn --processes 4`, SQL queries are crashed with mentioned error.
When I start gunicorn directly, e.g. `gunicorn -w 4 -b 127.0.0.1:5722 "supysonic.web:create_application()"`, all works fine.

At this point I have no idea what is the difference.
The former scenario invokes basically the same object:
```Python
    app = create_application()
    server(
        app, host=host, port=port, socket=socket, processes=processes, threads=threads
    ).run()
```
Could it be that Flask spawns 4 separate processes of gunicorn instead of gunicorn with 4 workers? 
May be we should use `--threads` instead of `--processes` for gunicorn?

**Comment by spl0k** [comment]
I think I know what's happening. The WSGI app (and then the SQL connection) is created before the worker(s). So when Gunicorn spawns its workers the connection is inherited from the parent process when the workers should open their own connection. This is the same problem than the one described in the comment you linked but in this case there's nothing you can set to fix the issue apart from starting Gunicorn directly as you already noted.
I'll look into it.

**Comment by trap000d** [comment]
Yep. Fortunately, `gunicorn blah-blah-blah` has running fine, so to me it's fair enough :)
Thanks a lot.

**Comment by trap000d** [comment]
I can confirm `supysonic-server`  command now works as intended, i.e. doesn't cause SQL crashes.
