### ISSUE TITLE
Add user on QNAP

### ISSUE THREAD

**Issue by Pingumania** [spl0k/supysonic#31]
Hi I installed supysonic on my QNAP TS-412 (ARM),

but if I try to add an user I get the following error. There are no special characters in the password.

```
[/opt] # /opt/supysonic/bin/supysonic-cli user add --admin pingumania
Password:
Confirm password:
Traceback (most recent call last):
  File "/opt/supysonic/bin/supysonic-cli", line 231, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/cmd.py", line 219, in onecmd
    return func(arg)
  File "/opt/supysonic/bin/supysonic-cli", line 51, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/opt/supysonic/bin/supysonic-cli", line 190, in user_add
    status = UserManager.add(self.__store, name, password, email, admin)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/site-packages/supysonic/managers/user.py", line 53, in add
    if store.find(User, User.name == name).one():
  File "/opt/local/lib/python2.7/site-packages/storm/store.py", line 1158, in one
    result = self._store._connection.execute(select)
  File "/opt/local/lib/python2.7/site-packages/storm/database.py", line 238, in execute
    statement = self.compile(statement, state)
  File "/opt/local/lib/python2.7/site-packages/storm/databases/sqlite.py", line 57, in compile_select_sqlite
    statement = compile_select(compile, select, state)
  File "/opt/local/lib/python2.7/site-packages/storm/expr.py", line 666, in compile_select
    tokens.append(compile(select.columns, state))
LookupError: unknown encoding:
```

**Comment by spl0k** [comment]
Triaging and closing old issues. Don't hesitate to reopen if you feel this still need to be investigated.
