### ISSUE TITLE
folder scan: unsupported format character

### ISSUE THREAD

**Issue by mgropp** [spl0k/supysonic#33]
When I try to run a folder scan in the CLI, I get the following exception:

    supysonic> folder scan owncloud-martin
    Traceback (most recent call last):
      File "bin/supysonic-cli", line 234, in <module>
        cli.cmdloop()
      File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
        stop = self.onecmd(line)
      File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
        return func(arg)
      File "bin/supysonic-cli", line 51, in method
        return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
      File "bin/supysonic-cli", line 150, in folder_scan
        scanner.scan(folder, TimedProgressDisplay(folder.name))
      File "/opt/supysonic/supysonic/scanner.py", line 60, in scan
        self.scan_file(path)
      File "/opt/supysonic/supysonic/scanner.py", line 140, in scan_file
        trroot = self.__find_root_folder(path)
      File "/opt/supysonic/supysonic/scanner.py", line 212, in __find_root_folder
        count = folders.count()
      File "/usr/local/lib/python2.7/dist-packages/storm/store.py", line 1264, in count
        return int(self._aggregate(lambda expr: Count(expr, distinct), expr))
      File "/usr/local/lib/python2.7/dist-packages/storm/store.py", line 1253, in _aggregate
        result = self._store._connection.execute(select)
      File "/usr/local/lib/python2.7/dist-packages/storm/databases/mysql.py", line 106, in execute
        return Connection.execute(self, statement, params, noresult)
      File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 241, in execute
        raw_cursor = self.raw_execute(statement, params)
      File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 374, in raw_execute
        self._run_execution(raw_cursor, args, params, statement)
      File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 388, in _run_execution
        self._check_disconnect(raw_cursor.execute, *args)
      File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 454, in _check_disconnect
        return function(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 159, in execute
        query = query % db.literal(args)
    ValueError: unsupported format character ''' (0x27) at index 58

**Comment by tkiapril** [comment]
This seems to happen when using MySQL.
I have executed (almost) exactly as follows:

```shell
sudo -uhttp git clone https://github.com/spl0k/supysonic.git app
sudo -uhttp virtualenv2 virtualenv
sudo virtualenv/bin/pip install flask storm MySQL-python pillow simplejson requests mutagen watchdog
sudo chown http:http -R virtualenv
sudo -uhttp virtualenv/bin/pip install -e app/
sudo mysql -e "create database supysonic; create user supysonic@localhost identified by 'password'; grant all privileges on supysonic.* to supysonic@localhost;"
mysql -usupysonic -p -Dsupysonic < supysonic/schema/mysql.sql
virtualenv/bin/supysonic-cli folder add music /data/files/music
virtualenv/bin/supysonic-cli folder scan
```

returns:
```
$ virtualenv/bin/supysonic-cli folder scan
Traceback (most recent call last):
  File "supysonic-venv/bin/supysonic-cli", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tki/supysonic/bin/supysonic-cli", line 232, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/tki/supysonic/bin/supysonic-cli", line 51, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "/home/tki/supysonic/bin/supysonic-cli", line 153, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name))
  File "/home/tki/supysonic/supysonic/scanner.py", line 60, in scan
    self.scan_file(path)
  File "/home/tki/supysonic/supysonic/scanner.py", line 140, in scan_file
    trroot = self.__find_root_folder(path)
  File "/home/tki/supysonic/supysonic/scanner.py", line 211, in __find_root_folder
    count = folders.count()
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/store.py", line 1264, in count
    return int(self._aggregate(lambda expr: Count(expr, distinct), expr))
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/store.py", line 1253, in _aggregate
    result = self._store._connection.execute(select)
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/databases/mysql.py", line 106, in execute
    return Connection.execute(self, statement, params, noresult)
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/database.py", line 241, in execute
    raw_cursor = self.raw_execute(statement, params)
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/database.py", line 374, in raw_execute
    self._run_execution(raw_cursor, args, params, statement)
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/database.py", line 388, in _run_execution
    self._check_disconnect(raw_cursor.execute, *args)
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/storm/database.py", line 454, in _check_disconnect
    return function(*args, **kwargs)
  File "/home/tki/supysonic-venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
ValueError: unsupported format character ''' (0x27) at index 58
```

my /etc/supysonic:
```ini
[base]
database_uri = mysql://supysonic:password@localhost/supysonic
scanner_extensions = mp3 ogg oga aac m4a flac wav wma aif aiff ape mpc shn

[webapp]
log_level = WARNING

[transcoding]
transcoder = ffmpeg -i %srcpath -ab %outratek -v 0 -f %outfmt -

[mimetypes]
mp3 = audio/mpeg
ogg = audio/ogg

[daemon]
log_level = WARNING
```
