### ISSUE TITLE
Transcoding variable style clashing with 'configparser' interpolation

### ISSUE THREAD

**Issue by tristan-k** [spl0k/supysonic#84]
I'm trying to run supysonic in a virtualenv on a raspberry pi 3 but I cant configure it because I will an get Traceback error when starting `supysonic-cli`. Also tried to install it outside the virtualenv and I'm getting the same error. Any suggestions?

```
$ mkdir -p ~/venv/supysonic
$ virtualenv ~/venv/supysonic
$ source ~/venv/supysonic/bin/activate
$ pip install flask storm pillow simplejson requests mutagen watchdog uwsgi future pony https://github.com/spl0k/supysonic/archive/master.tar.gz
$ mkdir -p ~/.config/supysonic/webcache ~/.config/supysonic/cgi-bin/ ~/.config/supysonic/schema
$ touch ~/.config/supysonic/supysonic-daemon.log
$ cd ~/.config/supysonic
$ git clone https://github.com/spl0k/supysonic supysonic-source
$ cp supysonic-source/config.sample ~/.supysonic
$ cp supysonic-source/cgi-bin/supysonic.wsgi cgi-bin/supysonic.wsgi
sqlite3 supysonic.db < supysonic-source/schema/sqlite.sql 
```

```
$ nano ~/.supysonic 
```

```
database_uri = sqlite:////home/pi/.config/supysonic/supysonic.db
cache-dir = /home/pi/.config/supysonic/webcache
log_file = /home/pi/.config/supysonic/supysonic-daemon.log
```

```
$ supysonic-cli 
Traceback (most recent call last):
  File "/home/pi/venv/supysonic/bin/supysonic-cli", line 18, in <module>
    config = IniConfig.from_common_locations()
  File "/home/pi/venv/supysonic/local/lib/python2.7/site-packages/supysonic/config.py", line 87, in from_common_locations
    return IniConfig(cls.common_paths)
  File "/home/pi/venv/supysonic/local/lib/python2.7/site-packages/supysonic/config.py", line 62, in __init__
    options = { k: self.__try_parse(v) for k, v in parser.items(section) }
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%outrate %srcpath -'
```

**Comment by spl0k** [comment]
Hi.

First of all (but it's not what is causing the error), you're installing `storm` which isn't needed anymore (replaced by `pony`). You're also creating unneeded folders.
I suppose the config you posted is just a snippet, not the whole file. You have a typo there, it's `cache_dir`, not `cache-dir`.

The problem comes from the `[transcoding]` section of your configuration. If you're not planning to use transcoding you can remove it altogether. If you want to keep transcoding you'll have to double every `%`, for instance use `%%outfmt` rather than `%outfmt`.

**Comment by spl0k** [comment]
The issue should now be fixed, you can ignore the workaround mentioned above. Configuration should now work as described in the documentation.

Thanks for reporting.
