### ISSUE TITLE
Error while library update with MySQL

### ISSUE THREAD

**Issue by sprnza** [spl0k/supysonic#87]
Hi there! I'm trying to move from Airsonic to Supysonic. On the initial library update I get this warning. What it could mean? Something has a wrong naming inside my collection?
```
Scanning 'MyLibrary': 9367 files scanned/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/dbapiprovider.py:255: Warning: (1366, "Incorrect string value: '\\xF0\\x9F\\x94\\xB4' for column 'title' at row 1")
  else: cursor.execute(sql, arguments)
/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/dbapiprovider.py:255: Warning: (1366, "Incorrect string value: '\\xF0\\x9F\\x94\\xB4.m...' for column 'path' at row 1")
  else: cursor.execute(sql, arguments)
```

**Comment by sprnza** [comment]
And then it fails with this error:
```
srvr ➜  ~ supysonic-cli folder scan MyLibrary
Scanning 'MyLibrary': 9367 files scanned/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/dbapiprovider.py:255: Warning: (1366, "Incorrect string value: '\\xF0\\x9F\\x94\\xB4' for column 'title' at row 1")
  else: cursor.execute(sql, arguments)
/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/dbapiprovider.py:255: Warning: (1366, "Incorrect string value: '\\xF0\\x9F\\x94\\xB4.m...' for column 'path' at row 1")
  else: cursor.execute(sql, arguments)
27344 files scannedTraceback (most recent call last):
  File "/usr/bin/supysonic-cli", line 4, in <module>
    __import__('pkg_resources').run_script('supysonic==0.3', 'supysonic-cli')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/EGG-INFO/scripts/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/supysonic/cli.py", line 77, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "<string>", line 2, in folder_scan
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 471, in new_func                            
    reraise(exc_type, exc, tb)                                                                                                    
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/utils/utils.py", line 87, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 460, in new_func
    try: return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/supysonic/cli.py", line 185, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/supysonic/scanner.py", line 98, in scan
    for track in Track.select(lambda t: t.root_folder == folder):
  File "<string>", line 2, in __iter__
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/utils/utils.py", line 58, in cut_traceback                     
    return func(*args, **kwargs)                                                                                                  
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 5506, in __iter__
    return iter(query._fetch())
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 5347, in _fetch
    used_attrs=translator.get_used_attrs())
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 3993, in _fetch_objects
    obj._db_set_(avdict)
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 4535, in _db_set_
    % (obj.__class__.__name__, attr.name, obj, old_dbval, new_dbval))
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/utils/utils.py", line 98, in throw
    raise exc                                                                                                                     
pony.orm.core.UnrepeatableReadError: Value of Track.title for Track[UUID('46ea0ed7-1691-4450-95b1-a1033f6a6296')] was updated outside of current transaction (was: '🔴', now: '????')    
```
Despite it says it's scanned 27K files, nothing has been added to the library.

**Comment by spl0k** [comment]
There are some issues with emojis in tags it seems. I was able to reproduce it with a MySQL database, however it works with SQLite and PostgreSQL.
Thanks for the report, I'll investigate further soon.

**Comment by sprnza** [comment]
Could you please post an update once you get it fixed. I'd like to stick with MySQL.

**Comment by spl0k** [comment]
That should be fixed with ba61281ba136ecf76bb8927afb79b9c8d640ff7a.
You'll have to either update the database tables using the `schema/migration/20180221.mysql.sql` script, or drop every table and recreate them with `schema/mysql.sql`.

**Comment by sprnza** [comment]
I've tried either update the databse or drop every table and with both variants I get this [error](http://share.speran.info/error.py)

**Comment by spl0k** [comment]
Could you please give me some additional information? I'll need:
- the Linux distribution (and version) you're running
- how did you install the `MySQLdb` python package? Was it through `pip`, your distrib package manager, some other mean? What's the package name and version?
- Are you running MySQL or MariaDB? Which version?

I'll also need you to give me the results of the following SQL commands, when connected to _Supysonic_'s database:
```
SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation\_%';
SHOW CREATE TABLE track;
```

Thank you.

**Comment by sprnza** [comment]
I'm running ArchLinux.
pymysql installed by pip
```
srvr ?  ~ pip show pymysql                                                                                                       
Name: PyMySQL                                                                                                                    
Version: 0.8.0                                                                                                                   
Summary: Pure Python MySQL Driver                                                                                                
Home-page: https://github.com/PyMySQL/PyMySQL/                                                                                   
Author: INADA Naoki                                                                                                              
Author-email: songofacandy@gmail.com                                                                                             
License: MIT                                                                                                                     
Location: /usr/lib/python3.6/site-packages
```
I'm running MariaDB with InnoDB engine.

[Errors](http://share.speran.info/9qpl8w11.sh) while trying to upgrade my database.

```
MariaDB [supysonic]> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation\_%';           
+--------------------------+--------------------+                                                                                
| Variable_name            | Value              |
+--------------------------+--------------------+
| character_set_client     | utf8               |
| character_set_connection | utf8               |
| character_set_database   | utf8mb4            |
| character_set_filesystem | binary             |
| character_set_results    | utf8               |
| character_set_server     | utf8mb4            |
| character_set_system     | utf8               |
| collation_connection     | utf8_general_ci    |
| collation_database       | utf8mb4_unicode_ci |
| collation_server         | utf8mb4_unicode_ci |
+--------------------------+--------------------+
10 rows in set (0.03 sec)
```

```
MariaDB [supysonic]> SHOW CREATE TABLE track;                                                                             [12/808]
+-------+-----------------------------------------------------------------------------------------------------------------[11/808]
--------------------------------------------------------------------------------------------------------------------------[10/808]
---------------------------------------------------------------------------------------------------------------------------[9/808]
---------------------------------------------------------------------------------------------------------------------------[8/808]
---------------------------------------------------------------------------------------------------------------------------[7/808]
---------------------------------------------------------------------------------------------------------------------------[6/808]
----------------------------------------------------+                                                                      [5/808]
| Table | Create Table                                                                                                     [4/808]
                                                                                                                           [3/808]
                                                                                                                           [2/808]
                                                                                                                           [1/808]


                                                    |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| track | CREATE TABLE `track` (
  `id` binary(16) NOT NULL,
  `disc` int(11) NOT NULL,
  `number` int(11) NOT NULL,
  `title` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `year` int(11) DEFAULT NULL,
  `genre` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration` int(11) NOT NULL,
  `album_id` binary(16) NOT NULL,
  `artist_id` binary(16) NOT NULL,
  `bitrate` int(11) NOT NULL,
  `path` varchar(4096) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `last_modification` int(11) NOT NULL,
  `play_count` int(11) NOT NULL,
  `last_play` datetime DEFAULT NULL,
  `root_folder_id` binary(16) NOT NULL,
  `folder_id` binary(16) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by spl0k** [comment]
From the trace you provided _Supysonic_ isn't using `pymysql` but some other package providing `MySQLdb`. I have assumed `mysqlclient` (installed through `pip`) for my tests. Correct me if I'm wrong.

Unfortunately I'm unable to reproduce on a fresh ArchLinux install, with the default MariaDB configuration.
This has something to do with how MySQL handles UTF-8, and probably some non-ASCII character in a file name. But even with '🔴' in several places I can scan a folder without any issue 🙁.

**Comment by sprnza** [comment]
@spl0k I did have mysqlclient installed, I've removed it and still get the error. Actually, I was tweaking my mysql setup a lot due to I have Nextcloud instance running on the same machine. Could instructions [here](https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html) be a problem?

**Comment by spl0k** [comment]
The only thing that could possibly affect Supysonic here are the settings on step 2. But even with these I still don't get any error.
Just to be sure, does the following SQL command reports only _Antelope_, only _Barracuda_, or both?

    SELECT NAME, FILE_FORMAT FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES WHERE NAME like "supysonic%";

Did you make some other changes to the MariaDB configuration?

I don't understand where this `utf8_general_ci` could come from, when all the tables are created with `utf8mb4_unicode_ci` and the connection encoding is [set as `utf8mb4`](https://github.com/spl0k/supysonic/blob/5188976e6f5aeec13de8d3c01b78d54c27cedd5c/supysonic/db.py#L459).

**Comment by sprnza** [comment]
I did tried to comment out mentioned lines in my.conf of no avail.
I'll try to revert to default config.
The command reports nothing:
```
MariaDB [supysonic]> SELECT NAME, FILE_FORMAT FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES WHERE NAME like "supysonic%";          
Empty set (0.03 sec)   
```
Actually I don't think I have this utf-8 symbol somethere in my file names, because my music library is being maintaned by [beets music library manager](https://github.com/beetbox/beets) and it converts all non ascii characters to underscores. There were some exceptions when it adds unrecognized music "as-is" but it were a few occasions.

**Comment by sprnza** [comment]
No luck with the default my.cnf. Actually I've got just these lines added in my custom my.cnf:
```
31,32d30
< datadir		= /var/lib/mysql
< innodb_large_prefix=true
< innodb_file_format=barracuda
< innodb_file_per_table=1
< tmpdir		= /var/lib/mysql/tmp
< innodb_buffer_pool_size = 256M
```

**Comment by sprnza** [comment]
```
MariaDB [supysonic]> show variables like 'collation%';                                                                                          
+----------------------+--------------------+                                                                                                   
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8_general_ci    |
| collation_database   | utf8mb4_unicode_ci |
| collation_server     | utf8mb4_general_ci |
+----------------------+--------------------+
3 rows in set (0.00 sec)
```

**Comment by sprnza** [comment]
As you see collation_connection is set to `utf8_general_ci` I'm not sure if it matters.

**Comment by sprnza** [comment]
And the issue is being fixed if I add
```
[mysqld]
init_connect='SET collation_connection = utf8_general_ci' 
```

**Comment by sprnza** [comment]
I'm not sure if it's related or not but I'm still unable to finish scanning:
```
srvr ➜  schema git:(master) supysonic-cli folder scan MyLibrary
Scanning 'MyLibrary': 27775 files scannedTraceback (most recent call last):
  File "/usr/bin/supysonic-cli", line 4, in <module>
    __import__('pkg_resources').run_script('supysonic==0.3', 'supysonic-cli')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/EGG-INFO/scripts/supysonic-cli", line 23, in <module>
    cli.onecmd(' '.join(sys.argv[1:]))
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/supysonic/cli.py", line 77, in method
    return func(** { key: vars(args)[key] for key in vars(args) if key != 'action' })
  File "<string>", line 2, in folder_scan
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 471, in new_func
    reraise(exc_type, exc, tb)
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/utils/utils.py", line 87, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 460, in new_func
    try: return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/supysonic/cli.py", line 185, in folder_scan
    scanner.scan(folder, TimedProgressDisplay(folder.name, self.stdout))
  File "/usr/lib/python3.6/site-packages/supysonic-0.3-py3.6.egg/supysonic/scanner.py", line 98, in scan
    for track in Track.select(lambda t: t.root_folder == folder):
  File "<string>", line 2, in __iter__
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 5506, in __iter__
    return iter(query._fetch())
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 5347, in _fetch
    used_attrs=translator.get_used_attrs())
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 3993, in _fetch_objects
    obj._db_set_(avdict)
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/orm/core.py", line 4535, in _db_set_
    % (obj.__class__.__name__, attr.name, obj, old_dbval, new_dbval))
  File "/usr/lib/python3.6/site-packages/pony-0.7.3-py3.6.egg/pony/utils/utils.py", line 98, in throw
    raise exc
pony.orm.core.UnrepeatableReadError: Value of Track.root_folder for Track[UUID('0048407c-637d-4cd0-8364-3f68052c753b')] was updated outside of current transaction (was: Folder[UUID('7956631d-124f-45bb-a290-c4d2ebadb1bd')], now: Folder[UUID('7956631d-124f-453f-3f3f-3f3febadb13f')])
```

**Comment by spl0k** [comment]
>```
>MariaDB [supysonic]> show variables like 'collation%';
>+----------------------+--------------------+
>| Variable_name        | Value              |
>+----------------------+--------------------+
>| collation_connection | utf8_general_ci    |
>| collation_database   | utf8mb4_unicode_ci |
>| collation_server     | utf8mb4_general_ci |
>+----------------------+--------------------+
>3 rows in set (0.00 sec)
>```
>
>As you see collation_connection is set to `utf8_general_ci` I'm not sure if it matters.

This should only affect the `mysql` command. I thought it should have picked a _utf8mb4_ collation for Supysonic's connections since we're explicitly setting the charset to _utf8mb4_, but your latest configuration seems to have proven me wrong.

As for your last error, I'm clueless 🤨
You can try to drop and recreate the whole database, as the various tests and configurations might have introduced some inconsistencies, but I'm not convinced.

**Comment by sprnza** [comment]
Moved to PostgreSQL.
